In [35]:
# Basic Data Exploration and Cleaning using Pandas
# ASSIGNMENT 1

In [36]:
import numpy as np
import pandas as pd

Loading the Dataset to a Pandas DataFrame

In [37]:
file= 'Combined_dataset.csv'
df=pd.read_csv(file)

Exploring the Dataset

In [38]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [39]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [40]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(1000, 24)

In [41]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [42]:
print("\nData Types:")
print(df.dtypes)

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [43]:
print("\nDataset Info:")
print(df.info())

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB
None

In [44]:
print(df.describe())

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

Checking for missing values

In [45]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

As visible, columns with non zero values have missing values.

Handling Missing Values

In [46]:
# Fill missing numerical values
df['discount'] = df['discount'].fillna(df['discount'].mean())
# Fill missing text values
df['seller_name'] = df['seller_name'].fillna('Unknown')
df['seller_information'] = df['seller_information'].fillna('Not Available')
df['what_customers_said'] = df['what_customers_said'].fillna('No Review')
df['variations'] = df['variations'].fillna('Not Available')
df['videos'] = df['videos'].fillna('No Video')

In [47]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [48]:
df= df.dropna()   # rows with any missing values get dropped #nothing dropped as missing values have been filled

In [49]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

Basic operations (filter rows, select columns)

In [50]:
selected_columns = df[['title','category','rating']]
print(selected_columns.head())

            title   category  rating
0     Lino Perros  backpacks     3.8
1  Tommy Hilfiger  backpacks     4.5
2           Lavie  backpacks     4.4
3          F Gear  backpacks     4.4
4       MYTRIDENT  bath-robe     4.7

In [51]:
#Filter rows where rating is less than 3
low_rating_products = df[df['rating']<3]
low_rating_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
11,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Sig███Ove███as,"[{""size"":""Super King""}]",No Video,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
12,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499,73.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",No Video,E-1███103███PIP█████████ IN███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
29,22278620,Tweens,Pack Of 2 Non Padded Medium Support All Day Co...,0.0,0,720,16.0,"""₹604.00""",INR,http://assets.myntassets.com/assets/images/222...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Bel███Lin███ies█████████.,"[{""size"":""30B"",""value"":""31.0in"",""value_name"":""...",No Video,B-5███Roo███aga█████████al ███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
41,18532334,Pepe Jeans,Men Green Printed Cotton Basic Briefs,0.0,0,459,20.0,"""₹298.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Vis███ St███,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...",No Video,3rd███oor███o. █████████Mai███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
45,21860658,EROTISSCH,Women Printed Laced Basic Briefs,0.0,0,899,40.0,"""₹539.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,AAK███INT███TES█████████LIM██████,"[{""size"":""S"",""value"":""27.5in"",""value_name"":""To...",No Video,Fir███Flo███ 38█████████nds███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs

In [52]:
#Filter rows where category is Earrings
fashion_prods = df[df['category'] == 'earrings']
fashion_prods.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
204,15720652,Rubans,Silver-Toned Dome Shaped Studs Earrings,3.8,21,1480,76.0,"""₹355.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":4,""4_stars"":...",No Review,AK ███erp███es,"[{""size"":""Onesize""}]",No Video,Plo███o 2███ 4t█████████ast███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
205,15713414,Crunchy Fashion,White Contemporary Studs Earrings,4.2,22,1998,68.0,"""₹639.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":2,""4_stars"":...",No Review,Cru███y F███ion█████████,"[{""size"":""Onesize""}]",No Video,2nd███oor███LOT█████████hin███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
206,15750524,Priyaasi,Rose Gold-Plated Dome Shaped Jhumkas,4.4,97,7999,74.0,"""₹2,079.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":3,""2_stars"":6,""3_stars"":4,""4_stars"":...",No Review,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]",No Video,PRI███DES███S P█████████MIT███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
207,15014966,Priyaasi,Gold-Toned & Gold Plated Contemporary Jhumkas ...,4.9,13,3949,76.0,"""₹947.00""",INR,http://assets.myntassets.com/assets/images/150...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]",No Video,PRI███DES███S P█████████MIT███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
208,10125243,KARATCART,White Gold-Plated Stone-Studded Beaded Chandel...,4.0,213,1282,62.0,"""₹487.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":22,""2_stars"":7,""3_stars"":32,""4_stars...",No Review,KOK███V G███AL █████████,"[{""size"":""Onesize""}]",No Video,Sho███58-███Sec█████████ain███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings

Remove duplicates

In [53]:
initial_rows= df.shape[0]

df= df.drop_duplicates()
final_rows= df.shape[0]

print(f"Rows before:{initial_rows}")
print(f"Rows after removing duplicates:{final_rows}")

Rows before:1000
Rows after removing duplicates:1000

Creating a derived column (total_amount = price * quantity)

In [54]:
df['total_amount']=  df['rating'] *df['ratings_count']
df[['rating','ratings_count','total_amount']].head()

   rating  ratings_count  total_amount
0     3.8             15          57.0
1     4.5             67         301.5
2     4.4            226         994.4
3     4.4           1052        4628.8
4     4.7             12          56.4

Save Cleaned Dataset

In [55]:
cleaned_file = 'cleaned_shopping_dataset.csv'
df.to_csv(cleaned_file, index=False)

print(f"Cleaned dataset saved as: {cleaned_file}")

Cleaned dataset saved as: cleaned_shopping_dataset.csv

Final Summary

In [56]:
print("\nFinal Dataset Shape:")
print(df.shape)

print("\nRemaining Missing Values:")
print(df.isnull().sum())

Final Dataset Shape:
(1000, 25)

Remaining Missing Values:
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
total_amount              0
dtype: int64

In [57]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'total_amount'],
      dtype='str')